---
name: Club IQ CI
---

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        working-directory: Backend
        run: ruff check .
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        working-directory: Backend
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run pytest
        working-directory: Backend
        run: python -m pytest -v
